services:
  webapi:
    build:
      context: .
      dockerfile: WebAPI/Dockerfile
    ports:
      - "7173:80"

  website:
    build:
      context: .
      dockerfile: Website/Dockerfile
    ports:
      - "5001:80"

  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "<password>"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - dbdata:/var/opt/mssql

volumes:
  dbdata: